{% set name = "airium" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/airium-{{ version }}.tar.gz
  sha256: ccab36b798b6cce3d0c5074e52ce8059f6e82991caae4985f42cadfad80b1de4

build:
  entry_points:
    - airium = airium.__main__:entry_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - airium
  commands:
    - pip check
    - airium --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/kamichal/airium
  summary: Easy and quick html builder with natural syntax correspondence (python->html). No templates needed. Serves pure pythonic library with no dependencies.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmacdope
    - mikemhenry
